# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_product_instrutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='instrutor',
            field=models.CharField(default='a', max_length=100, verbose_name='Instrutor'),
            preserve_default=False,
        ),
    ]
